fix(HQT-419): fix ui bugs
alievdenis1/NutritionTime_Dev-test pull request #16
Opened 2024-08-26 05:40 UTC by ArealtemDeveloper

2024-08-26 18:39 UTC, dimonhawk123 requested changes

2024-08-26 18:39 UTC, dimonhawk123 commented on src/entities/Recipe/DetailedCardRecipe/RecipeDetailsTabs.vue
> +								{{ item.quantity }} шт.
Вместо `шт.` использовать интернационализацию

2024-08-26 18:39 UTC, dimonhawk123 commented on src/entities/Recipe/DetailedCardRecipe/stores/recipeStore.ts
> +        const ingredientAmount = Number(ingredient.amount.replace(/[^+\d]/g, ''))
Можно эту часть кода вынести в отдельную функцию и вызывать внутри reduce. Тогда не нужно будет два раза проходить по массиву. Всё можно будет обработать за один проход.

2024-08-26 18:39 UTC, dimonhawk123 commented on src/entities/Recipe/DetailedCardRecipe/stores/recipeStore.ts
>      })
Как будто бы лучше разделить логику поиска рецепта и добавления поля totalWeight.
Работать тогда лучше через ссылку.
```
const currentRecipeInfo = recipes.value.find(recipe => recipe.id === recipeId)
currentRecipeInfo.totalWeight = calculateTotalWeight(currentRecipeInfo ?.ingredients)
return currentRecipeInfo
```
Проверить, что всё работает корректно и totalWeight проставляется

2024-08-28 18:22 UTC, ArealtemDeveloper commented on src/entities/Recipe/CreateRecipe/recipe-models/IngredientsRecipe/CreateRecipeIngredients.vue
> +			type: ingredient.amount?.includes('г.') ? QuantityType.WEIGHT : QuantityType.QUANTITY,
Пока сделал реализацию, чтобы хотя бы отвязаться от строки, но вообще в будущем нужно будет типы вынести куда-то в общее место, чтобы был доступ и в моковых данных и здесь, в рамках этой задачи не стал этого делать.

2024-08-29 17:56 UTC, dimonhawk123 commented on src/entities/Recipe/CreateRecipe/recipe-models/IngredientsRecipe/CreateRecipeIngredients.vue
> +			amount: props.isExclusionMode ? t('excluded') : `${ingredient.quantity} ${ingredient.type === QuantityType.WEIGHT ? 'г.' : 'шт.'}`,
Давай тут 'г.' и 'шт.' тоже сделаем через t('unitGrams') и t('unitPieces')

2024-08-29 17:56 UTC, dimonhawk123 commented on src/entities/Recipe/CreateRecipe/recipe-models/timeRecipe/CreateRecipeTime.vue
> +									@input="truncateCookingTime"
У меня IDE ругается на типизацию тега input
Показывает, что типизация функции `truncateCookingTime` не соответствует типизации свойства `@input`

2024-08-29 17:56 UTC, dimonhawk123 commented on src/entities/Recipe/CreateRecipe/recipe-models/timeRecipe/CreateRecipeTime.vue
> +	}
Один из вариантов типизации, чтобы пропали ошибки
```
const truncateCookingTime = (event: Event) => {
	const target = (<HTMLInputElement>event.target)

	if(target?.value === '000') {
		target.value = '0'
	}
```

2024-08-29 17:56 UTC, dimonhawk123 commented on src/entities/Recipe/CreateRecipe/recipe-models/timeRecipe/CreateRecipeTime.vue
> +const truncateReadyTime = (event: InputEvent) => {
С этой функцией аналогичная ситуация

2024-08-29 17:56 UTC, dimonhawk123 commented on src/entities/Recipe/DetailedCardRecipe/stores/recipeStore.ts
> +    if (weight.includes('шт')) {
У нас же теперь у сущности `ingredient` есть свойство `type`
Поэтому нам не нужно делать такие проверки (через 'шт')
Можно написать следующим образом:
```
    if (ingredient.type === 'quantity') {
        return 0
    }
```

2024-08-30 18:23 UTC, dimonhawk123 approved these changes

2024-08-30 18:23 UTC, merged